######################################################################
# Automatically generated by qmake (2.01a) Thu Feb 6 08:32:16 2014
######################################################################

QT += testlib sql
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += \
    helper.h \
    auth.h
SOURCES += TestCase01.cpp \
    helper.cpp \
    auth.cpp
