######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 5 12:53:55 2014
######################################################################

QT += testlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Auth.h
SOURCES += Auth.cpp TestCase01.cpp
