######################################################################
# Automatically generated by qmake (2.01a) Thu Feb 6 08:32:16 2014
######################################################################

QT += testlib sql
TEMPLATE = app
TARGET = Unittest
DEPENDPATH += .
INCLUDEPATH += .
CONFIG   -= app_bundle

# Input
HEADERS += \
    ../src/helper.h \
    ../src/auth.h
SOURCES += TestCase01.cpp \
    ../src/helper.cpp \
    ../src/auth.cpp
