######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 5 04:59:16 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
# HEADERS += TestCase01.h
SOURCES += TestCase01.h TestCase01.cpp
QT += testlib
