######################################################################
# Automatically generated by qmake (3.0) Sun Feb 2 07:12:44 2014
######################################################################

TEMPLATE = app
TARGET = HelloQtCpp
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += widgets