######################################################################
# Automatically generated by qmake (2.01a) Thu Feb 6 08:32:16 2014
######################################################################

QT += testlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Auth.h
SOURCES += TestCase01.cpp Auth.cpp
